[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 100

[variables]
NODE_ENV = "production"
PORT = "3000"
REACT_APP_API_URL = "https://bubble-ads-backend-production.up.railway.app" 