[build]
builder = "nixpacks"

[deploy]
startCommand = "serve -s build"
numReplicas = 1

[variables]
NODE_ENV = "production"
PORT = "3000"
REACT_APP_API_URL = "https://bubble-ads-backend-production.up.railway.app" 