[build]
builder = "NODE"

[deploy]
startCommand = "SKIP_PREFLIGHT_CHECK=true npm run build && npm start"
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "3000"
CI = "false"
SKIP_PREFLIGHT_CHECK = "true"
GENERATE_SOURCEMAP = "false" 