[build]
builder = "NODE"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "3000"
CI = "false"
SKIP_PREFLIGHT_CHECK = "true"
GENERATE_SOURCEMAP = "false" 