services:
  # Frontend Web Service
  - type: web
    name: bubble-ads-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production

  # Backend Web Service  
  - type: web
    name: bubble-ads-backend
    env: node
    region: ohio
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: bubble-ads-db
          property: connectionString
      - key: PORT
        value: 5000

databases:
  - name: bubble-ads-db
    databaseName: bubble-ads
    plan: free 