[phases.setup]
nixPkgs = ["nodejs_18", "npm_9"]
aptPkgs = ["ca-certificates"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
cmd = "node index.js"

[variables]
NODE_ENV = "production"
PORT = "5000" 