[build]
builder = "NIXPACKS"
buildCommand = "npm cache clean --force && rm -rf node_modules && npm install --force"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "5000" 