[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"
numReplicas = 1

[variables]
NODE_ENV = "production"
PORT = "5000"
MONGODB_URI = "mongodb+srv://lyfesaverscoin:gB5gN_4mj5YXyqS@cluster0.hgud2.mongodb.net/bubble-ads" 