[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps --force"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "5000"
NODE_VERSION = "18.x"
NPM_VERSION = "9.x" 