[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"
buildCommand = "npm install --legacy-peer-deps"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
PORT = "5000" 