services:
  - type: web
    name: bubble-ads-backend
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: node index.js
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://lyfesaverscoin:gB5gN_4mj5YXyqS@cluster0.hgud2.mongodb.net/bubble-ads
      - key: JWT_SECRET
        value: bubble-ads-jwt-secret-key-2024 